const ENV = {
  VITE_PICKLE_MAIN_SERVER_URL: import.meta.env.VITE_PICKLE_MAIN_SERVER_URL,
  VITE_PICKLE_MYDATA_URL: import.meta.env.VITE_PICKLE_MYDATA_URL,
  VITE_PICKLE_BACKTEST_URL: import.meta.env.VITE_PICKLE_BACKTEST_URL,
  VITE_PICKLE_REALTIME_URL: import.meta.env.VITE_PICKLE_REALTIME_URL,
};
export default ENV;
