name: Main Branch Deployment

on:
  push:
    branches:
      - main
      - deploy
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/react-app/Frontend
          git fetch --all
          git pull origin main
          cd pickle-frontend
          npm install
          npm run build
          pm2 restart react-app || pm2 start npm --name "react-app" -- run preview
