name: Main Branch Deployment

on:
  push:
    branches:
      - main
      - deploy
      
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: |
        cd Frontend/pickle-frontend
        npm install
      
    - name: Build
      run: |
        cd Frontend/pickle-frontend
        npm run build
      
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key" --delete Frontend/pickle-frontend/dist/ ${USER}@${HOST}:/home/ubuntu/react-app/Frontend/pickle-frontend
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          cd /home/ubuntu/react-app/Frontend/pickle-frontend &&
          npm install &&
          pm2 restart react-app || pm2 start npm --name "react-app" -- run preview'